export { default as About} from './About/About'
export { default as Footer} from './Footer/Footer'
export { default as Header} from './Header/Header'
export { default as Skills} from './Skills/Skills'
export {default as Skills_2} from './Skills_2/Skills_2'
export { default as Testimonials} from './Testimonials/Testimonial'
export { default as Work} from './Work/Work'
